implement run command

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -719,6 +719,50 @@ enter()
                     "$shell_to_exec" -l 2>&3
 )
 
+run()
+(
+    command="$1"
+
+    echo "$base_toolbox_command: checking if container $toolbox_container exists" >&3
+
+    if ! toolbox_image=$($prefix_sudo podman inspect \
+                                 --format "{{.ImageName}}" \
+                                 --type container \
+                                 $toolbox_container 2>&3); then
+        echo "$base_toolbox_command: container $toolbox_container not found" >&2
+        echo "Use the 'create' command to create a toolbox." >&2
+        echo "Try '$base_toolbox_command --help' for more information." >&2
+        exit 1
+    fi
+
+    echo "$base_toolbox_command: container $toolbox_container was created from image $toolbox_image" >&3
+
+    [ "$toolbox_image" != "" ] 2>&3 && check_image_for_volumes "$toolbox_image"
+
+    echo "$base_toolbox_command: trying to start container $toolbox_container" >&3
+
+    if ! $prefix_sudo podman start $toolbox_container >/dev/null 2>&3; then
+        echo "$base_toolbox_command: failed to start container $toolbox_container" >&2
+        exit 1
+    fi
+
+    if [ "$DBUS_SYSTEM_BUS_ADDRESS" != "" ]; then
+        set_dbus_system_bus_address="--env DBUS_SYSTEM_BUS_ADDRESS=$DBUS_SYSTEM_BUS_ADDRESS"
+    fi
+
+    set_environment=$(create_environment_options)
+
+    echo "$base_toolbox_command: trying to run '$command' in container $toolbox_container" >&3
+
+    $prefix_sudo podman exec \
+            $set_dbus_system_bus_address \
+            $set_environment \
+            --interactive \
+            --tty \
+            $toolbox_container \
+            capsh --caps="" -- -c "$command"
+)
+
 
 list_images()
 (
@@ -1031,6 +1075,9 @@ usage()
     echo "               enter [--container <name>]"
     echo "                     [--release <release>]"
     echo "   or: toolbox [-v | --verbose]"
+    echo "               run [-c | --container <name>]"
+    echo "                   [-r | --release <release>]"
+    echo "   or: toolbox [-v | --verbose]"
     echo "               list [-c | --containers]"
     echo "                    [-i | --images]"
     echo "   or: toolbox rm [-a | --all]"
@@ -1169,6 +1216,34 @@ case $op in
             exit_if_extra_operand "$1"
             update_container_and_image_names
             enter
+        fi
+        exit
+        ;;
+    run )
+        if is_integer "$podman_pid"; then
+            forward_to_host
+        else
+            while has_prefix "$1" -; do
+                case $1 in
+                    -c | --container )
+                        shift
+                        exit_if_missing_argument --container "$1"
+                        toolbox_container=$1
+                        ;;
+                    -r | --release )
+                        shift
+                        exit_if_missing_argument --release "$1"
+                        arg=$(echo $1 | sed "s/^F\|^f//" 2>&3)
+                        exit_if_non_positive_argument --release "$arg"
+                        release=$arg
+                        ;;
+                    * )
+                        exit_if_unrecognized_option $1
+                esac
+                shift
+            done
+            update_container_and_image_names
+            run "$*"
         fi
         exit
         ;;
